# Generated by Django 5.0.6 on 2024-05-28 16:15

from django.db import migrations, connection, models

def set_initial_student_id(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE sqlite_sequence SET seq = 999999 WHERE name = 'app_student';")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/app')),
            ],
        ),
        migrations.RunPython(set_initial_student_id),
    ]
